#!/bin/bash
if [ "$#" -ne 1 ]; then
	echo "Illegal number of parameters"
	echo "Usage: "`basename "$0"`" script-url"
	exit 1
fi

d=/tmp/scripts-$RANDOM
f=script-$RANDOM
u=$1
mkdir -p $d
wget -q -O $d/$f $u
if [ "$?" -ne 0 ]; then
	echo "Could not download file \"$u\""
	rm -rf $d
	exit 1
fi
sbcl --script $d/$f
rm -rf $d
unset d
unset f
unset u
